<a href="https://colab.research.google.com/github/Catal2s/PREPROCESAMIENTO-DE-DATOS_001D-2026/blob/main/PDD_Actividad_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [14]:
df=pd.read_csv('1.1.6. Archivo para actividad práctica.csv')
df

,S.NO,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,1,Mike Tyson,USA,1,NaN,boxing,1990,28.6
1,2,Buster Douglas,USA,2,NaN,boxing,1990,26.0
2,3,Sugar Ray Leonard,USA,3,NaN,boxing,1990,13.0
3,4,Ayrton Senna,Brazil,4,NaN,auto racing,1990,10.0
4,5,Alain Prost,France,5,NaN,auto racing,1990,9.0
...,...,...,...,...,...,...,...,...
296,297,Stephen Curry,USA,6,9,Basketball,2020,74.4
297,298,Kevin Durant,USA,7,10,Basketball,2020,63.9
298,299,Tiger Woods,USA,8,11,Golf,2020,62.3
299,300,Kirk Cousins,USA,9,>100,American Football,2020,60.5
300,301,Carson Wentz,USA,10,>100,American Football,2020,59.1

In [20]:
#Muestra las estadísticas básicas de los valores númericos.
df.describe()

             S.NO  Current Rank         Year  earnings ($ million)
count  301.000000    301.000000   301.000000            301.000000
mean   151.000000      5.448505  2005.122924             45.516279
std     87.035433      2.850995     9.063563             33.525337
min      1.000000      1.000000  1990.000000              8.100000
25%     76.000000      3.000000  1997.000000             24.000000
50%    151.000000      5.000000  2005.000000             39.000000
75%    226.000000      8.000000  2013.000000             59.400000
max    301.000000     10.000000  2020.000000            300.000000

In [16]:
#Ver el tipo de dato de cada columna.
#object = texto
#int64 = números enteros
#float = números decimales
df.dtypes

S.NO                      int64
Name                     object
Nationality              object
Current Rank              int64
Previous Year Rank       object
Sport                    object
Year                      int64
earnings ($ million)    float64
dtype: object

In [18]:
#Primeras 5 filas del dataframe.
df.head()

,S.NO,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,1,Mike Tyson,USA,1,NaN,boxing,1990,28.6
1,2,Buster Douglas,USA,2,NaN,boxing,1990,26.0
2,3,Sugar Ray Leonard,USA,3,NaN,boxing,1990,13.0
3,4,Ayrton Senna,Brazil,4,NaN,auto racing,1990,10.0
4,5,Alain Prost,France,5,NaN,auto racing,1990,9.0

In [19]:
#Ultimas 5 filas del dataframe.
df.tail()

,S.NO,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
296,297,Stephen Curry,USA,6,9,Basketball,2020,74.4
297,298,Kevin Durant,USA,7,10,Basketball,2020,63.9
298,299,Tiger Woods,USA,8,11,Golf,2020,62.3
299,300,Kirk Cousins,USA,9,>100,American Football,2020,60.5
300,301,Carson Wentz,USA,10,>100,American Football,2020,59.1

In [22]:
df['earnings ($ million)'].describe()

count    301.000000
mean      45.516279
std       33.525337
min        8.100000
25%       24.000000
50%       39.000000
75%       59.400000
max      300.000000
Name: earnings ($ million), dtype: float64